export const types = {
    
    USER_DETAILS_LOADING: 'USER_DETAILS_LOADING',
    USER_DETAILS_SUCCESS: 'USER_DETAILS_SUCCESS',
    USER_DETAILS_FAIL: 'USER_DETAILS_FAIL',

    REPOSITORY_LIST_LOADING: 'REPOSITORY_LIST_LOADING',
    REPOSITORY_LIST_SUCCESS: 'REPOSITORY_LIST_SUCCESS',
    REPOSITORY_LIST_FAIL: 'REPOSITORY_LIST_FAIL',
    
}